FROM node:12

WORKDIR /app

COPY package*.json ./

ENV PORT=7680
ENV BD_SEMINARIO_HOST='192.168.230.128'
ENV BD_SEMINARIO_PORT=3306
ENV BD_SEMINARIO_USER='root'
ENV BD_SEMINARIO_PASSWORD='admin'
ENV BD_SEMINARIO_DB='EFS'

RUN npm install

COPY . .

EXPOSE $PORT

CMD ["npm", "start"]